

package userinterface.RestaurantAdminRole;


import Business.DeliveryMan.DeliveryManDirectory;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Restaurant restaurant;
    UserAccount userAccount;
    DeliveryManDirectory deliveryManDirectory;
    
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,Restaurant restaurant,DeliveryManDirectory deliveryManDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.restaurant = restaurant;
        this.deliveryManDirectory = deliveryManDirectory;
        valueLabel.setText(this.restaurant.getName());
      
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ManageRestaurantJButton = new javax.swing.JButton();
        ManageMenuJButton = new javax.swing.JButton();
        ManageOrdersJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        ManageRestaurantJButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ManageRestaurantJButton.setText("Manage Restaurant Info >>");
        ManageRestaurantJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageRestaurantJButtonActionPerformed(evt);
            }
        });
        add(ManageRestaurantJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 300, -1));

        ManageMenuJButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ManageMenuJButton.setText("Manage menu >>");
        ManageMenuJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageMenuJButtonActionPerformed(evt);
            }
        });
        add(ManageMenuJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 220, -1));

        ManageOrdersJButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ManageOrdersJButton.setText("Manage Orders >>");
        ManageOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageOrdersJButtonActionPerformed(evt);
            }
        });
        add(ManageOrdersJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 153, 51));
        enterpriseLabel.setText("Restaurant :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 200, 30));

        valueLabel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 98, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ManageRestaurantJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageRestaurantJButtonActionPerformed
        // TODO add your handling code here:
        ManageRestaurantInfoJPanel manageRestaurantInfoJPanel = new ManageRestaurantInfoJPanel(userProcessContainer, restaurant);
        userProcessContainer.add("manageRestaurantInfoJPanel", manageRestaurantInfoJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_ManageRestaurantJButtonActionPerformed

    private void ManageMenuJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageMenuJButtonActionPerformed
        ManageMenuJPanel manageMenuJPanel = new ManageMenuJPanel(userProcessContainer, restaurant);
        userProcessContainer.add("manageMenuJPanel", manageMenuJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageMenuJButtonActionPerformed

    private void ManageOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageOrdersJButtonActionPerformed
        ManageOrdersJPanel manageOrdersJPanel = new ManageOrdersJPanel(userProcessContainer, userAccount,restaurant,deliveryManDirectory);
        userProcessContainer.add("manageOrders", manageOrdersJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageOrdersJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageMenuJButton;
    private javax.swing.JButton ManageOrdersJButton;
    private javax.swing.JButton ManageRestaurantJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
